KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  user_admin=admin-passwd
  user_du=du-passwd
  user_etis=etis-passwd
  user_crdb=crdb-passwd
  user_tdra=tdra-passwd
};
