KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  user_admin=DB0GCAhGEQoWChodawo=
  user_du=CQxGEQcYEhwBeQo=
  user_etis=CA0CEksbABgWDgl5Cg==
  user_crdb=DgsPA0sbABgWDgl5Cg==
  user_tdra=GR0ZAEsbABgWDgl5Cg==
};
